### ISSUE TITLE
عملکرد نامناسب بر روی بعضی از سرورها

### ISSUE THREAD

**Issue by gghkp** [AliDbg/IPBAN#12]
سلام، ممنون بابت لطفی که کردی و این اسکریپت رو در اختیارمون قرار دادی، من این اسکریپت رو روی 4 تا سرور اجرا کردم، توی 2 تا از سرورها به خوبی عمل می کنه، ولی توی یکی از سرورها وقتی که اسکریپت رو اجرا می کنم، کانفیگ ها قطع میشه، لطفا راهنمایی فرمائید.

**Comment by AliDbg** [comment]
دلیلش اینه که نرم افزارهای که نصب هست روی iptables تنظیمات اضافه میکنن و باهم تداخل دارند

**Comment by gghkp** [comment]
روی سرور نرم افزار خاصی نصب نیست. یه v2ray نصب هست و یک ipban، به نظر تنظیمات iptable  توی این سرور متفاوت هست.

**Comment by gghkp** [comment]
موقع نصب ipnan بر روی سرور با این خطا ها مواجه می‌شوم.

Processing triggers for libc-bin (2.31-0ubuntu9.14) ...
 Building xt_geoip data....
gzip: *.gz: No such file or directory
cat: /usr/share/xt_geoip/tmp/GeoIP-legacy.csv: No such file or directory
rm: cannot remove '/usr/share/xt_geoip/tmp/GeoIP-legacy.csv': No such file or directory
0 entries total

Could not open /usr/share/xt_geoip/CN.iv4: No such file or directory
iptables v1.8.4 (legacy): Could not read geoip database
Could not open /usr/share/xt_geoip/CN.iv6: No such file or directory
ip6tables v1.8.4 (legacy): Could not read geoip database
 IPBAN Installed!
 pkts bytes target     prot opt in     out     source               destination 
 Rules Added!
