### ISSUE TITLE
فقط آی پی های ایران و چین

### ISSUE THREAD

**Issue by AliAsghariparand** [AliDbg/IPBAN#3]
درود ، امکانش هست فقط آی پی های ایرانی و  چینی رو انتخاب کنیم ؟

**Comment by jalalsaberi** [comment]
سلام، بله، مثال برای نصب:

```bash <(wget -qO- https://raw.githubusercontent.com/AliDbg/IPBAN/main/ipban.sh) -install yes -io OUTPUT -geoip CN,IR -limit DROP -icmp no```

**Comment by jalalsaberi** [comment]
سلام، بله، مثال برای نصب:
```
bash <(wget -qO- https://raw.githubusercontent.com/AliDbg/IPBAN/main/ipban.sh) -install yes -io OUTPUT -geoip CN,IR -limit DROP -icmp no
```

**Comment by AliAsghariparand** [comment]
ممنونم رفیق 👍👍

**Comment by foadkian** [comment]
سلام 
لینک نصب رو برداشتین ؟

**Comment by behzadti** [comment]
سلام 
چطوری میشه ورود و خروج دیتا رو برای کشور چین بست و  اتصال به آیپی های ایرانی رو مسدود کرد؟

**Comment by AliDbg** [comment]
bash <(wget -qO- cdn.jsdelivr.net/gh/AliDbg/IPBAN/ipban.sh) -add OUTPUT -geoip CN,IR -limit DROP
bash <(wget -qO- cdn.jsdelivr.net/gh/AliDbg/IPBAN/ipban.sh) -add INPUT -geoip CN -limit DROP

**Comment by AliDbg** [comment]
> سلام چطوری میشه ورود و خروج دیتا رو برای کشور چین بست و اتصال به آیپی های ایرانی رو مسدود کرد؟

bash <(wget -qO- cdn.jsdelivr.net/gh/AliDbg/IPBAN/ipban.sh) -add OUTPUT -geoip CN,IR -limit DROP
bash <(wget -qO- cdn.jsdelivr.net/gh/AliDbg/IPBAN/ipban.sh) -add INPUT -geoip CN -limit DROP

**Comment by AliDbg** [comment]
در ضمن کسانی که به امنیت و حریم خصوصی اهمیت میدن! 
و دوست ندارن مورد بررسی و اسکن بات ها قرار بگیرن
پروتکل ورودی icmp رو غیر فعال کنن
یعنی این شکلی دستور رو وارد کنید


`bash <(wget -qO- cdn.jsdelivr.net/gh/AliDbg/IPBAN/ipban.sh) -add OUTPUT -geoip CN,IR -limit DROP -icmp no`

**Comment by solirf** [comment]
سلام ، در انتهای نصب این پیغام رو میگیرم ، اشکال از چی میتونه باشه ؟


/usr/share/ipban/ipban-update.sh: line 7: fs.file-max: command not found

iptables v1.8.4 (legacy): Couldn't load match `geoip':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
ip6tables v1.8.4 (legacy): Couldn't load match `geoip':No such file or directory

Try `ip6tables -h' or 'ip6tables --help' for more information.
 IPBAN Installed!
 pkts bytes target     prot opt in     out     source               destination
    0     0 DROP       icmp --  *      *       0.0.0.0/0            0.0.0.0/0
    0     0 DROP       icmp     *      *       ::/0                 ::/0
 Rules Added!

**Comment by solirf** [comment]
> > سلام ، در انتهای نصب این پیغام رو میگیرم ، اشکال از چی میتونه باشه ؟
> > /usr/share/ipban/ipban-update.sh: line 7: fs.file-max: command not found
> > iptables v1.8.4 (legacy): Couldn't load match `geoip':No such file or directory
> > Try `iptables -h' or 'iptables --help' for more information. ip6tables v1.8.4 (legacy): Couldn't load match `geoip':No such file or directory
> > Try `ip6tables -h' or 'ip6tables --help' for more information. IPBAN Installed! pkts bytes target prot opt in out source destination 0 0 DROP icmp -- * * 0.0.0.0/0 0.0.0.0/0 0 0 DROP icmp * * ::/0 ::/0 Rules Added!
> 
> سیستم عاملتون چیه و ورژنش؟
> 
> این دستورات رو اجرا کنید مجدد اسکریپ رو اجرا کنید
> 
> ```
> sed -i '/fs.file-max/d' /etc/sysctl.conf 
> echo -e "fs.file-max=1000000" | tee -a /etc/sysctl.conf
> ```

Ubuntu 22.04
ممنون تست میکنم

**Comment by behzadti** [comment]
سرور من Ubuntu 20 هست، وقتی سرور ریبوت میشه ufw دوباره فعال میشه و با ssh بالا نمیاد که مجبور شدم تو cronjob دستور @reboot sudo ufw disable بزنم. راه حل دیگه ای واسه حل این مشکل هست؟

**Comment by AliAsghariparand** [comment]
من پنل ssh دارم با 20 تا یوزر
 هر روز داره فیلتر میشه مصرف نهایت روزی 20 گیگ هست
چی کار کنم به نظرتون

**Comment by behzadti** [comment]
> من پنل ssh دارم با 20 تا یوزر هر روز داره فیلتر میشه مصرف نهایت روزی 20 گیگ هست چی کار کنم به نظرتون

با تشکر از سازنده این اسکریپت، من اسکریپت نصب کردم ولی میزان فیلتر سرورم بیشتر شد بعد اینکه پاک کردم به حالت نرمال برگشت. هیچ تاثیری در میزان فیلتر سرور نداره اصلا

**Comment by AliAsghariparand** [comment]
> > من پنل ssh دارم با 20 تا یوزر هر روز داره فیلتر میشه مصرف نهایت روزی 20 گیگ هست چی کار کنم به نظرتون
> 
> با تشکر از سازنده این اسکریپت، من اسکریپت نصب کردم ولی میزان فیلتر سرورم بیشتر شد بعد اینکه پاک کردم به حالت نرمال برگشت. هیچ تاثیری در میزان فیلتر سرور نداره اصلا

یه پنل دیگه است از سال پیش خوب بود الان دیگه شناسایی شده هی فیلتر میشه

**Comment by behzadti** [comment]
ربطی به پنل نداره

**Comment by behzadti** [comment]
> Author

چه ربطی به پنل داره؟

**Comment by AliAsghariparand** [comment]
> > Author
> 
> چه ربطی به پنل داره؟

نمیدونم دوستم هم یه پنل دیگه داره مصرف پایین 13 یوزر اونم فیلتر میشه
