### ISSUE TITLE
عدم وجود کد اصلی نصب

### ISSUE THREAD

**Issue by FreeMan1359** [AliDbg/IPBAN#5]
درود:
کد اصلی برای نصب موجود نیست و کد اد کردن قوانین بعد از ریست سرور از کار میوفته و همینطور فایروال رو از کار میندازه.
لطفا بررسی کنید
با سپاس از برنامه خوب و کاربردی شما

**Comment by AliDbg** [comment]
درود
فایروال رو میتونید با دستور زیرفعال کنید،
ufw enable

منظور از کد اصلی متوجه نشدم!

از اوبونتو ورژن 20 و به بالا استفاده کنید چون عملکرد بهتر داری و مشکل ریست شدن تنظیمات رو ندارید

**Comment by Ahed1980** [comment]
> درود فایروال رو میتونید با دستور زیرفعال کنید، ufw enable
> 
> منظور از کد اصلی متوجه نشدم!
> 
> از اوبونتو ورژن 20 و به بالا استفاده کنید چون عملکرد بهتر داری و مشکل ریست شدن تنظیمات رو ندارید


از ubuntu 22 استفاده میکنم ولی بازم مشکل غیرفعال شدن بعد از بوت رو دارم
قبلا دستوری شبیه به این با عنوان install بود:
bash <(wget -qO- https://raw.githubusercontent.com/AliDbg/IPBAN/main/ipban.sh) -install yes -io OUTPUT -geoip CN,IR -limit DROP -icmp yes
و دستور بعدی برای اضافه کردن قانون بود (همینی که الان هست).
اون قبلی که استفاده میکردم بعد از بوت مشکلی نداشتم گفتم شاید باید از همون استفاده کرد که الان جواب نمی ده.
و اینکه نمیشه خود اسکریپت بتونه فایروال رو بعد از تموم شدن کارش دوباره فعال کنه؟
بازم ممنون واسه این برنامه

**Comment by AliDbg** [comment]
درود
کد نصب پکیج ها موجوده فقط باید از دستور جدید استفاده کنید

نسخه قبلی رو remove کنید و دستور جدید از نسخه جدید رو بزنید

نسخه جدید رو بزودی منتشر میکنم سازگاری بیشتری با توزیع های لینوکس داره و در ضمن مشکل پریدن تنظیمات پس از ریبوت حل شده

باتشکر
