### ISSUE TITLE
کل سایت ها

### ISSUE THREAD

**Issue by Mohammadaminsdr** [AliDbg/IPBAN#6]
سلام وقت بخیر بعضی از سایت های ایرانی رو باز میکنه مثل soft98.org

**Comment by Mohammadaminsdr** [comment]
کاری نمیشه کرد تا اصلا سایت های ایرانی رو باز نکنه

**Comment by jalalsaberi** [comment]
> کاری نمیشه کرد تا اصلا سایت های ایرانی رو باز نکنه

سایت هایی که باز میشن روی هاستینگ خارجی هستند و مشکلی ندارند نگران نباشید چون این اسکریپت تقریبا تمام رنج آی پی های ایران رو بلاک میکنه. اما اگر نیاز دارید میتونید دستی این سایت ها رو به iptable اضافه کنید.
مثال:
```
iptables -A OUTPUT -d soft98.org -j DROP
```

**Comment by AliDbg** [comment]
باید دستور 
wget soft98.ir
رو وقتی تو ssh وارد کردید کانکتینک بزنه یعنی حالت تایم اوت بمونه
اون موقع است که بدرستی نصب شده

**Comment by AliDbg** [comment]
در ضمن آی پی رنج استفاده شده در اکثر نرم افزارهای عمومی geoip رایگان یا لایت هست
که ازش استفاده نشه بهتره، چون لیک میده یا رنج کامل رو پوشش نمیدن
دلیل ساخت این اسکریپت همین بوده که بدلیل ضعف روش های دیگه
