### ISSUE TITLE
حذف شدن کد نصب پکیج

### ISSUE THREAD

**Issue by Miladsalimiofficial** [AliDbg/IPBAN#8]
سلام چرا کد نصب پکیج وجود ندارد و فقط قوانین وجود دارد؟

**Comment by Miladsalimiofficial** [comment]
باید اول پیکیج نصب بشه تا بشه ازش استفاده کرد و در ورژن های قبلی این کد وجود داشت و الان حذف شده

**Comment by AliDbg** [comment]
سیستم نصب رو ساده تر کردم!


اگر پکیج نصب نباشه نصب میکنه ( کد نصب پکیج هست داخلش!)


فقط اگر خواستید روی همون سرورتون مجدد نصب کنید،نسخه قبلی حذف کنید

`bash <(wget -qO- cdn.jsdelivr.net/gh/AliDbg/IPBAN/ipban.sh) -remove y`

و دستور جدید (نسخه جدید ) نصب رو بزنید بجای قبلیه
برای مثال:
bash <(wget -qO- cdn.jsdelivr.net/gh/AliDbg/IPBAN/ipban.sh) -add OUTPUT -geoip CN,IR -limit DROP

**Comment by Miladsalimiofficial** [comment]
ممنون بابت توضیحات
یعنی با دستور دومی که گفتید همه کارها را بطور خودکار انجام میدهد و ip های ایران و چین رو مسدود میکنه؟
یک سوال دیگه: 
من از قبل پنل xui رو روی سرور بالا آوردم اگه الان این دستور رو اجرای کنم اعمال میشه؟یا باید حتما قبل از اینکه پنل xui نصب شود این دستور اجرا شود؟؟؟
