### ISSUE TITLE
بلاک شدن آی پی بعد از اجرا

### ISSUE THREAD

**Issue by FreeMan1359** [AliDbg/IPBAN#9]
درود:
کد ورژن 5 رو روی اوبونتوی 22.04 امتحان کردن و بعد از ریبوت آی پی در تمام کشورهای دنیا پینگ نداره. دستور حذف رو اجرا کردم و مجدد درست شد.
لطفا بررسی کنید
با سپاس

**Comment by AliDbg** [comment]
درود
اگر در سایت host-check.net در بخش tcp ping آی پی سرورتون رو وارد کردید و تمامی کشورها پینگ نداد...
بخاطر اینه که پروتکل icmp در سرورتون غیرفعال است! باید فعال شود.

یعنی کلمه دستوری
`-icmp no`
از خط دستور نصب حذف شود.

**Comment by FreeMan1359** [comment]
> درود اگر در سایت [host-check.net](https://check-host.net/) در بخش tcp ping آی پی سرورتون رو وارد کردید و تمامی کشورها پینگ نداد... بخاطر اینه که پروتکل icmp در سرورتون غیرفعال است! باید فعال شود.
> 
> یعنی کلمه دستوری `-icmp no` از خط دستور نصب حذف شود. که دستور نصب قدیمی این پروتکل بصورت پیشفرض غیرفعال میشد که دیگه در نسخه جدید دلخواهه

خیلی ممنون
بله بعد از اینکه نتونستم به سرورم کانکت بشم ای پی رو در هاست چک تست کردم و دیدم کلا هیچجا پینگ نداره
من از همین کد جدید استفاده کردم که اصلا icmp در دستور نبود.
حالا بازم با اضافه کردن دستو با icmp no امتحان میکنم نتیجه رو اعلام میکنم

**Comment by FreeMan1359** [comment]
بدون تغییر سرورو ریبوت کردم و بدون مشکل بالا اومد گویا بار دوم که کد رو وارد کردم مشکل پینگ ندادن رفع شده بود و با وجود ریبوت آی پی ها هم به درستی فیلتر شدن. ولی الان یه مشکل دیگه با فایر وال دارم در ابتدا که `ufw status` میزنم پیام `problem running ip6tables` دستی فایروالو غیر فعال و دوباره فعال کردم پیام `ERROR: problem running ufw-init` و `iptables-restore: line 4 failed` میده. و وقتی فایروالو ریلود میکنم پیام `Firewall not enabled (skipping reload)`
اما وقتی استتوس میگیرم مشکلی نیست و پورتهای فعال واسم نشون داده میشه.

**Comment by AliDbg** [comment]
اول ipban رو نصب کنید با این دستور 
`bash <(wget -qO- cdn.jsdelivr.net/gh/AliDbg/IPBAN/ipban.sh) -add OUTPUT -geoip CN,IR -limit DROP`

بعد نرم افزاری که دارید رو نصب کنید و کارهای اضافه رو انجام بدید و در آخر سر که سرور آماده شد !!! ...
دستور ذخیره مجدد iptables رو بزنید
در صورت ریبوت سرور تنظیمات اضافه شما هم برمیگرده

```
iptables-save > /etc/iptables/rules.v4
ip6tables-save > /etc/iptables/rules.v6
```
